spring:
  application:
    name: config-service-github
  profiles: 
    active: default
  cloud:
    config:
      enabled: true
      uri: http://host.docker.internal:9296
      search-path:
      - poc-microservico-requisitado
